Simplify the slurm epilog logging
While the epilog script writes normally to stdout and stderr,
a higher-level script takes care of redirecting to systemd's journal.

diff --git a/ansible/roles/slurm_install/templates/99-gpu-last-job-cleanup.j2 b/ansible/roles/slurm_install/templates/99-gpu-last-job-cleanup.j2
--- a/ansible/roles/slurm_install/templates/99-gpu-last-job-cleanup.j2
+++ b/ansible/roles/slurm_install/templates/99-gpu-last-job-cleanup.j2
@@ -1,38 +1,30 @@
 #!/usr/bin/env sh
-set -eu
+set -e
 
-SCRIPTNAME="$(basename $0)"
-
-log () {
-	logger -s -t "slurm_epilog_$SCRIPTNAME" "$1"
-}
+description="GPU cleanup for user $SLURM_JOB_USER, nodes $SLURM_JOB_NODELIST"
+echo "Starting $description."
 
 if ! command -v nvidia-smi > /dev/null 2>&1; then
-	log "Skipping as this node is not gpu-equipped."
+	echo "Skipping as nvidia-smi is not installed on this node."
 	exit 0
 fi
 
 if [ $SLURM_JOB_UID -eq 0 ]; then
-	log "Skipping for user root."
+	echo "Skipping for user root."
 	exit 0
 fi
 
 remaining_jobs="$(squeue -h -u "$SLURM_JOB_USER" -w "$SLURM_JOB_NODELIST")"
 if [ "$remaining_jobs" ]; then
-	log "Skipping as this is not the last job for user $SLURM_JOB_USER on nodes $SLURM_JOB_NODELIST."
+	echo "Skipping as this is not the user's last job on the target nodes."
 	exit 0
 fi
 
-log "Starting for user $SLURM_JOB_USER."
-
 gpu_count=$(nvidia-smi -L | wc -l)
-gpu_ids="$(seq --separator="," 0 $((gpu_count - 1)))"
-killed_pids="$(runuser -u "$SLURM_JOB_USER" -- fuser -k /dev/nvidia{$gpu_ids})"
+nvidia_devices="$(seq --separator=" " 0 $((gpu_count - 1)) | sed -E 's|([[:digit:]]+)|/dev/nvidia\1|g')"
 
-if [ "$killed_pids" ]; then
-	log "Killed pids $killed_pids."
-else
-	log "Nothing to kill."
-fi
+# Suppress the exit status of fuser as it returns non-zero when there are no
+# processes to kill
+runuser -u "$SLURM_JOB_USER" -- fuser -k $nvidia_devices || true
 
-log "Finished for user $SLURM_JOB_USER."
+echo "Finished $description."
